fix if condition of scenario test step
Signed-off-by: Masaya Kataoka <ms.kataoka@gmail.com>

diff --git a/.github/workflows/BuildAndRun.yaml b/.github/workflows/BuildAndRun.yaml
--- a/.github/workflows/BuildAndRun.yaml
+++ b/.github/workflows/BuildAndRun.yaml
@@ -148,11 +148,12 @@ jobs:
           # execute scenarios but ignore the return code
           ./src/scenario_simulator_v2/.github/workflows/workflow.sh ./src/scenario_simulator_v2/test_runner/scenario_test_runner/config/optional_workflow.txt global_frame_rate:=20 || true
           ./src/scenario_simulator_v2/.github/workflows/generate_workflow_report.sh /tmp/scenario_workflow/optional_workflow
-          echo failure=$(grep -c "<failure"  /tmp/scenario_workflow/optional_workflow/failure_report.md) >> $GITHUB_OUTPUT
+          failure_count=$(grep -c "<failure" /tmp/scenario_workflow/optional_workflow/failure_report.md || echo 0)
+          echo "failure=$failure_count" >> $GITHUB_OUTPUT
         shell: bash
 
       - uses: actions/github-script@v7
-        if: ${{ steps.optional-scenario-test.outputs.failure != '' && steps.optional-scenario-test.outputs.failure | int > 0 && matrix.runs_on == 'ubuntu-22.04' }} # @TODO Support unit/integration test with ARM CPU.
+        if: ${{ steps.optional-scenario-test.outputs.failure != '' && steps.optional-scenario-test.outputs.failure > 0 && matrix.runs_on == 'ubuntu-22.04' }}
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
@@ -166,7 +167,7 @@ jobs:
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: commentBody
-            })
+            });
 
       - name: Upload Lcov result
         uses: actions/upload-artifact@v4
