Fix (mistakenly deleted) scenario test

diff --git a/.github/workflows/BuildAndRun.yaml b/.github/workflows/BuildAndRun.yaml
--- a/.github/workflows/BuildAndRun.yaml
+++ b/.github/workflows/BuildAndRun.yaml
@@ -98,7 +98,7 @@ jobs:
 
       - name: Colcon test
         # ARM testing is currently broken
-        if: ${{ matrix.runs_on != 'ubuntu-22.04-arm' }}
+        if: matrix.runs_on != 'ubuntu-22.04-arm'
         run: |
           source /opt/ros/${{ matrix.rosdistro }}/setup.bash
           source install/local_setup.bash
@@ -107,7 +107,7 @@ jobs:
         shell: bash
 
       - name: generate gcov report for sonarcloud
-        if: ${{ matrix.runs_on != 'ubuntu-22.04-arm' }}
+        if: matrix.runs_on != 'ubuntu-22.04-arm'
         run: gcovr -r src/scenario_simulator_v2 build --sonarqube coverage.xml
 
       - name: Show test result
@@ -119,16 +119,45 @@ jobs:
         shell: bash
 
       - name: Scenario test
-        if: ${{ matrix.runs_on != 'ubuntu-22.04-arm' }}
+        if: matrix.runs_on != 'ubuntu-22.04-arm'
         run: |
           source install/setup.bash
           source install/local_setup.bash
           ./src/scenario_simulator_v2/.github/workflows/workflow.sh ./src/scenario_simulator_v2/test_runner/scenario_test_runner/config/workflow.txt global_frame_rate:=20
         shell: bash
 
+      - name: Scenario test (optional)
+        id: optional-scenario-test
+        if: matrix.runs_on != 'ubuntu-22.04-arm'
+        run: |
+          source install/setup.bash
+          source install/local_setup.bash
+          # execute scenarios but ignore the return code
+          ./src/scenario_simulator_v2/.github/workflows/workflow.sh ./src/scenario_simulator_v2/test_runner/scenario_test_runner/config/optional_workflow.txt global_frame_rate:=20 || true
+          ./src/scenario_simulator_v2/.github/workflows/generate_workflow_report.sh /tmp/scenario_workflow/optional_workflow
+          echo failure=$(grep -c "<failure"  /tmp/scenario_workflow/optional_workflow/failure_report.md) >> $GITHUB_OUTPUT
+        shell: bash
+
+      - uses: actions/github-script@v7
+        if: steps.optional-scenario-test.outputs.failure > 0 && matrix.runs_on != 'ubuntu-22.04-arm'
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const fs = require('fs');
+            let commentBody = fs.readFileSync('/tmp/scenario_workflow/optional_workflow/failure_report.md', 'utf8');
+            if (commentBody) {
+              commentBody = '## Failure optional scenarios\n> [!NOTE]\n> This is an experimental check and does not block merging the pull-request. \n> But, please be aware that this may indicate a regression.\n' + commentBody;
+            }
+            await github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: commentBody
+            })
+
       - name: Upload Lcov result
         uses: actions/upload-artifact@v4
-        if: ${{ matrix.runs_on != 'ubuntu-22.04-arm' }}
+        if: matrix.runs_on != 'ubuntu-22.04-arm'
         with:
           name: lcov-${{ matrix.cmake_build_type }}
           path: lcov
@@ -136,7 +165,7 @@ jobs:
 
       - name: Upload Gcov result
         uses: actions/upload-artifact@v4
-        if: ${{ matrix.runs_on != 'ubuntu-22.04-arm' }}
+        if: matrix.runs_on != 'ubuntu-22.04-arm'
         with:
           name: coverage${{ matrix.cmake_build_type }}.xml
           path: coverage.xml
@@ -145,7 +174,7 @@ jobs:
       - name: SonarQube Scan
         uses: SonarSource/sonarqube-scan-action@v4.2.1
         # In ARM build, SonarQube result should be same as x86 build because no test runs
-        if: ${{ matrix.runs_on != 'ubuntu-22.04-arm' }}
+        if: matrix.runs_on != 'ubuntu-22.04-arm'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
